### ISSUE TITLE
specifying css file to use for eBook

### ISSUE THREAD

**Issue by mrchristian** [transpect/epubtools-frontend#1]
Hi,

In the epub-config.xml file can I specify the css file to use for my eBook.

Reason I am asking is I have several css files for different outputs: print, web, mobile, ebook.

Thanks

Simon

**Comment by gimsieke** [comment]
It will use any CSS files that are included by `<link rel="stylesheet">`, and also any `<style>` element content. I don’t think that epubtools already ignores rules that are for print; maybe there should be a `p:delete` that removes just these (and possibly other) rules in the parsed CSS. I’m assigning this to Fränze so that she can filter the parsed CSS for EPUB generation [approximately here](https://github.com/transpect/epubtools/blob/master/modules/create-ops/xpl/create-ops.xpl#L269).

**Comment by mrchristian** [comment]
Hi,

Thanks :-) Much appreciated.

For not I'll comment out css file I dont want to be used in the .xhtml file as an intermediary step.

Cheers

Simon
